### ISSUE TITLE
`curator tag` trying to tag language for external subrip files

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#12]
I'm not sure what curator thinks it can do in this case?

```console
$ chrt -b 0 curator tag -s all -t language Risk\ \(2017\).en.srt
...
```

I wouldn't normally try to tag an SRT file of course, but if you're using some shell glob you will inevitably get one. This results in this plan:

![2023-02-26T20:48:01,412364629+03:00-fs8](https://user-images.githubusercontent.com/191754/221427264-d7dd5e96-a9c5-4dba-ac05-10a499706e2b.png)

There is nothing to tag in this case because it's just a text file. If the subrip is inside an mkv container then it makes sense...

**Comment by AlexAltea** [comment]
My bad, I tried to move away from using extensions to detect the format type, but forgot to add checks to ensure .SRT files are skipped. There might be other similar formats, but it's hard to find them beforehand.

Fixed in https://github.com/AlexAltea/curator/commit/8af45b6f47fda68192c246af6f83feeb166d7647.
